<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <AssemblyName>NSMediaUpdater.Providers.Dbi</AssemblyName>
    <RootNamespace>NSMediaUpdater.Providers.Dbi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NSMediaUpdater.Core\NSMediaUpdater.Core.csproj" />
  </ItemGroup>
</Project>
